#!/usr/bin/env python3
"""
Installation script for LLDB Objective-C Tools.

This script manages the .lldbinit file to automatically load the Objective-C
debugging commands when LLDB starts. Scripts are copied to ~/.lldb-objc/ for
a stable installation path.

Usage:
    ./install.py            # Install to ~/.lldb-objc and update ~/.lldbinit
    ./install.py --uninstall # Remove from ~/.lldbinit and ~/.lldb-objc
    ./install.py --status    # Check installation status
"""

import os
import sys
import shutil
import argparse
from pathlib import Path

# Configuration - source locations (where install.py lives)
SOURCE_DIR = Path(__file__).parent.absolute()
SOURCE_SCRIPTS_DIR = SOURCE_DIR / "scripts"

# Installation locations (permanent home)
INSTALL_DIR = Path.home() / ".lldb-objc"
INSTALLED_SCRIPTS_DIR = INSTALL_DIR / "scripts"
LLDBINIT_PATH = Path.home() / ".lldbinit"

# Import version from source scripts directory
sys.path.insert(0, str(SOURCE_SCRIPTS_DIR))
try:
    from version import __version__
except ImportError:
    __version__ = "unknown"

# Marker comments for our block in .lldbinit
MARKER_START = "# BEGIN lldb-objc auto-generated section"
MARKER_END = "# END lldb-objc auto-generated section"


def get_lldbinit_commands():
    """Generate the commands to add to .lldbinit."""
    commands = [
        MARKER_START,
        f"# LLDB Objective-C Tools v{__version__}",
        f"# Auto-generated by install.py - DO NOT EDIT THIS SECTION",
        f"command script import {INSTALLED_SCRIPTS_DIR}",
        MARKER_END,
    ]
    return "\n".join(commands) + "\n"


def read_lldbinit():
    """Read the current .lldbinit file."""
    if not LLDBINIT_PATH.exists():
        return ""
    return LLDBINIT_PATH.read_text()


def write_lldbinit(content):
    """Write content to .lldbinit file."""
    # Create backup
    if LLDBINIT_PATH.exists():
        backup_path = LLDBINIT_PATH.with_suffix(".lldbinit.backup")
        LLDBINIT_PATH.rename(backup_path)
        print(f"Created backup: {backup_path}")

    LLDBINIT_PATH.write_text(content)
    print(f"Updated: {LLDBINIT_PATH}")


def remove_existing_section(content):
    """Remove any existing lldb-objc section from .lldbinit."""
    lines = content.split("\n")
    result = []
    in_section = False

    for line in lines:
        if line.strip() == MARKER_START:
            in_section = True
            continue
        elif line.strip() == MARKER_END:
            in_section = False
            continue

        if not in_section:
            result.append(line)

    # Remove trailing empty lines but keep one if file is not empty
    while len(result) > 1 and result[-1].strip() == "":
        result.pop()

    return "\n".join(result)


def install():
    """Install the LLDB commands to ~/.lldb-objc and update .lldbinit."""
    print(f"Installing LLDB Objective-C Tools v{__version__}...")
    print(f"Source: {SOURCE_DIR}")
    print(f"Install to: {INSTALL_DIR}")
    print(f"LLDB config: {LLDBINIT_PATH}")

    # Verify source scripts directory and required files exist
    if not SOURCE_SCRIPTS_DIR.exists():
        print(f"Error: Scripts directory not found: {SOURCE_SCRIPTS_DIR}", file=sys.stderr)
        return False

    required_files = [
        "__init__.py",
        "objc_breakpoint.py",
        "objc_sel.py",
        "objc_cls.py",
        "objc_call.py",
        "objc_watch.py",
        "objc_protos.py",
        "objc_pool.py",
        "objc_instance.py",
        "objc_explain.py",
        "objc_decompile.py",
        "objc_llm.py",
        "objc_utils.py",
        "objc_core.py",
        "version.py",
    ]

    for filename in required_files:
        file_path = SOURCE_SCRIPTS_DIR / filename
        if not file_path.exists():
            print(f"Error: Required file not found: {file_path}", file=sys.stderr)
            return False

    # Copy scripts to permanent install location
    print(f"\nCopying scripts to {INSTALL_DIR}...")
    if INSTALL_DIR.exists():
        shutil.rmtree(INSTALL_DIR)
    INSTALL_DIR.mkdir(parents=True)

    # Copy the scripts directory
    shutil.copytree(SOURCE_SCRIPTS_DIR, INSTALLED_SCRIPTS_DIR)
    print(f"  Copied {len(list(INSTALLED_SCRIPTS_DIR.glob('*.py')))} Python files")

    # Read existing .lldbinit
    content = read_lldbinit()

    # Remove any existing section
    content = remove_existing_section(content)

    # Add newline before our section if file is not empty
    if content.strip():
        content = content.rstrip() + "\n\n"

    # Append our commands
    content += get_lldbinit_commands()

    # Write back
    write_lldbinit(content)

    print("\nInstallation complete!")
    print("\nThe following commands are now available in LLDB:")
    print("  obrk       - Set breakpoints on Objective-C methods")
    print("  osel       - Find selectors in Objective-C classes")
    print("  ocls       - Find Objective-C classes by pattern")
    print("  ocall      - Call Objective-C methods from the command line")
    print("  owatch     - Set auto-logging breakpoints (method watcher)")
    print("  oprotos    - Find classes conforming to a protocol")
    print("  opool      - Find instances in autorelease pools")
    print("  oinstance  - Inspect Objective-C object instances")
    print("  oexplain   - Explain disassembly via LLM")
    print("  odecompile - Decompile function via LLM")
    print("  oreload    - Reload all commands (useful for development)")
    print("\nStart LLDB to use the commands.")

    return True


def uninstall():
    """Remove the LLDB commands from .lldbinit and ~/.lldb-objc."""
    print(f"Uninstalling LLDB Objective-C Tools...")
    print(f"Install dir: {INSTALL_DIR}")
    print(f"LLDB config: {LLDBINIT_PATH}")

    # Remove .lldbinit section
    if LLDBINIT_PATH.exists():
        content = read_lldbinit()
        if MARKER_START in content:
            content = remove_existing_section(content)
            write_lldbinit(content)
            print("Removed section from .lldbinit")
        else:
            print("No lldb-objc section found in .lldbinit")
    else:
        print("No .lldbinit file found")

    # Remove installed scripts
    if INSTALL_DIR.exists():
        shutil.rmtree(INSTALL_DIR)
        print(f"Removed {INSTALL_DIR}")
    else:
        print(f"No install directory found at {INSTALL_DIR}")

    print("\nUninstallation complete!")

    return True


def check_status():
    """Check if the tools are installed."""
    print(f"LLDB Objective-C Tools v{__version__}")
    print(f"Source: {SOURCE_DIR}")
    print(f"Install dir: {INSTALL_DIR}")
    print(f"LLDB config: {LLDBINIT_PATH}")
    print()

    # Check install directory
    scripts_installed = INSTALLED_SCRIPTS_DIR.exists()
    if scripts_installed:
        py_files = list(INSTALLED_SCRIPTS_DIR.glob("*.py"))
        print(f"Scripts: {len(py_files)} files in {INSTALLED_SCRIPTS_DIR}")
    else:
        print(f"Scripts: NOT INSTALLED (no {INSTALL_DIR})")

    # Check .lldbinit
    if not LLDBINIT_PATH.exists():
        print("LLDB config: NOT CONFIGURED (.lldbinit does not exist)")
        return

    content = read_lldbinit()

    if MARKER_START in content:
        print("\nConfiguration in .lldbinit:")
        # Extract and display our section
        lines = content.split("\n")
        in_section = False
        for line in lines:
            if line.strip() == MARKER_START:
                in_section = True
            if in_section:
                print(f"  {line}")
            if line.strip() == MARKER_END:
                break

        if scripts_installed:
            print("\nStatus: INSTALLED")
        else:
            print("\nStatus: PARTIALLY INSTALLED (scripts missing)")
    else:
        print("LLDB config: NOT CONFIGURED (no lldb-objc section)")
        print("\nStatus: NOT INSTALLED")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description=f"Install LLDB Objective-C Tools v{__version__}",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  ./install.py              Install to ~/.lldbinit
  ./install.py --uninstall  Remove from ~/.lldbinit
  ./install.py --status     Check installation status
        """
    )

    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--uninstall",
        action="store_true",
        help="Remove LLDB Objective-C Tools from .lldbinit"
    )
    group.add_argument(
        "--status",
        action="store_true",
        help="Check installation status"
    )

    args = parser.parse_args()

    try:
        if args.uninstall:
            success = uninstall()
        elif args.status:
            check_status()
            success = True
        else:
            success = install()

        sys.exit(0 if success else 1)

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
